- appium/sample-scripts/python/device_finder.py
- appium/sample-scripts/python/testdroid_android.py
- appium/sample-scripts/python/testdroid_ios.py
Python appium samples modified, to search for available free device. Customers testing the system, does not need to try out devices manually.
> Automatic free device finder added

- appium/sample-scripts/python/testdroid_android.py
Add possibility to use environment variables to pass values to the script.
> Improve Appium native example in Python

- README.md
- appium/sample-scripts/python/README.md
Initial guides for testing native apps for ios and android with Python and Appium.
> Python Appium native apps documentation

- appium/sample-scripts/ruby/README.md
README file for Ruby samples explaining the various sample files.
> short Ruby examples tutorial

- README.md
- appium/sample-scripts/csharp/README.md
- appium/sample-scripts/java/README.md
- appium/sample-scripts/python/README.md
- appium/sample-scripts/ruby/README.md
Root README updates formatting.
Language specific READMEs updated with testdroid_apiKey desired capability documentation.
> READMEs updated with apiKey 

- appium/sample-scripts/python/testdroid_android.py
- appium/sample-scripts/python/testdroid_ios.py
- appium/sample-scripts/python/testdroid_safari.py
Update Java samples to use apiKey instead of username and password.
> Java sample updated to use apiKey

- image-recognition/README.md
> links to testdroid.com added

- appium/sample-scripts/python/testdroid_chrome.py
Changed site and functional test.
> testdroid.com changes too often breaking test

- appium/sample-scripts/python/testdroid_chrome.py
* Switched to Appium webdriver, 
* screenshots taken in NATIVE mode so they get stored to cloud, 
* screenshot method fixed and taken to use
* new wait until method for waiting searched xpath element
> chrome screenshots stored to cloud, uses appium webdriver

- appium/sample-scripts/python/testdroid_safari.py
Safari test similar to Chrome test.
> Safari test update

- xcode/calculator.xcodeproj/project.pbxproj
- xcode/calculator/ViewController.swift
- xcode/calculator/operations.swift
- xcode/calculatorUITests/calculatorUITests.swift
- xcode/calculatorUITests/extensions.swift
also  updated swift version and syntax
> update to xcuitest example added extension to help tapping by coordinate

- robot-framework/run-tests-android.sh
- robot-framework/run-tests-ios.sh
At the moment the log files and screenshots are not showing correctly. After merging this the robot framework job config's result files can be updated to match the appium server side job config's results part.
> fix for gathering the results

- self-play-tests/appium/python/.gitignore
- self-play-tests/appium/python/BitbarSampleAppTest.py
- self-play-tests/appium/python/TestdroidAppiumTest.py
- self-play-tests/appium/python/createAndroidZip.sh
- self-play-tests/appium/python/createiOSZip.sh
- self-play-tests/appium/python/requirements.txt
- self-play-tests/appium/python/run-tests_android.sh
- self-play-tests/appium/python/run-tests_ios.sh
The test itself doesn't do anything else than launch the app and take
screenshots. The assumption is that the game automatically starts
playing itself. Otherwise the self-play mechanism needs to be triggered
either via run-tests.sh or test script itself.
> Self play test based on Appium Python Client added

- samples/testing-frameworks/appium/server-side/javascript/webdriver.io/README.md
> Typo fix in README

- samples/testing-frameworks/flutter/run-tests-ios.sh
Cleaned Flutter sample run-tests-ios.sh -script.
> modified flutter run-tests-ios.sh

- samples/testing-frameworks/detox/react-native/README.md
deprecation text to Detox README file
> deprecating support for Detox in README file

- samples/testing-frameworks/appium/client-side/csharp/README.md
- samples/testing-frameworks/appium/client-side/csharp/Test123/TestdroidAndroidSample.csproj
- samples/testing-frameworks/appium/client-side/csharp/Test123/Tests.cs
- samples/testing-frameworks/appium/client-side/csharp/Test123/packages.config
Cleanup Appium CS for C# sample
> Sdcb 6255 cleanup appium cs c# sample

- samples/testing-frameworks/appium/client-side/java/src/test/java/com/testdroid/appium/ios/sample/IosAppiumExampleTest.java
> Update Appium Java sample iOS

- samples/testng-parallel-mobile-tests/README.md
- samples/testng-parallel-mobile-tests/pom.xml
- samples/testng-parallel-mobile-tests/src/main/java/base/BaseTest.java
- samples/testng-parallel-mobile-tests/src/test/java/SimpleGoogleTest.java
-Bumped dependencies versions in order to fix security issue
-Added simple README
-Bitbar api key is now environment variable
-Previous test didn't work because of google chrome dialog which was displayed when entering google site. Changed the test content and replaced site to [web-testing-target](https://bitbar.github.io/web-testing-target/).
> SDCB-3378-Security-issue-fix-and-cleanup

- samples/testing-frameworks/detox/react-native/package.json
Currently detox sample generates lot of security issues while still not beeing supported. It seems also that detox still won't work on iOS real device (https://github.com/wix/Detox/issues/95).
Launching detox sample generates tones of problem (mainly because of depreciations). I tried to cleanup this sample but got stuck when launching builded test and couldn't find any working solution. Having in mind that detox sample is not supported and doesn't work on ios real device the solution for now in my opinion is to raise packages' versions (which i did in the pull request) just to get rid of security issues and if we'll decide to support detox one day we can use the code i got stuck with or rewrite the sample.
> SDCB-6354-Detox-security-issues-fix

- apps/android/src/testdroid-sample-app/build.gradle
- apps/android/src/testdroid-sample-app/gradle.properties
- apps/android/src/testdroid-sample-app/gradle/wrapper/gradle-wrapper.properties
- apps/android/src/testdroid-sample-app/testdroidSample/build.gradle
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/AndroidManifest.xml
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/AB_About.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/AN_Answer.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/DI_DeviceInfo.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/ES_ExternalStorage.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/FC_Functions.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/GA_Game.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/HY_Hybrid.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/MM_MainMenu.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/NA_Native.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/SE_Settings.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/WE_Wear.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/adapters/DevicePropertyExpandableArrayAdapter.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/game/GameLoopThread.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/game/GameView.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/models/DeviceProperty.java
- apps/android/src/testdroid-sample-app/testdroidSample/src/main/java/com/testdroid/sample/android/models/DevicePropertyGroup.java
- Upgrade gradle from 2.2.1 to 7.3.3
- Migrate to AndoidX
- Removal of unused variables, libraries and methods
> Sdcb 6271 cleanup android testdroid sample app

- samples/testing-frameworks/appium/server-side/ruby/README.md
The sample works fine and doesn't produce any security issues. I've only added minor changes to README to make it more clear what to do with builded .zips.
> Sdcb 6263 cleanup appium ss ruby sample

- samples/testing-frameworks/appium/server-side/ruby/run-tests_android.sh
- samples/testing-frameworks/appium/server-side/ruby/run-tests_ios.sh
Removed symlinks from scripts.
> SDCB-8125-Server-side-automated-tests---ignoring-TEST-all.xml

- samples/testing-frameworks/appium/server-side/image-recognition/pom.xml
> SDCB-8809-Fix-vulnerability-in-image-recognition

- samples/testing-frameworks/appium/server-side/javascript/biometricInstrumentation/webdriver.io/ios.wdio.conf.js
- samples/testing-frameworks/appium/server-side/javascript/biometricInstrumentation/webdriver.io/package-lock.json
- samples/testing-frameworks/appium/server-side/javascript/biometricInstrumentation/webdriver.io/package.json
- samples/testing-frameworks/appium/server-side/javascript/biometricInstrumentation/webdriver.io/test/specs/iOS/biometricFail.e2e.js
- samples/testing-frameworks/appium/server-side/javascript/biometricInstrumentation/webdriver.io/test/specs/iOS/biometricPass.e2e.js
- samples/testing-frameworks/appium/server-side/javascript/webdriver.io/ios.conf.js
- samples/testing-frameworks/appium/server-side/javascript/webdriver.io/package-lock.json
- samples/testing-frameworks/appium/server-side/javascript/webdriver.io/package.json
- samples/testing-frameworks/appium/server-side/javascript/webdriver.io/run-tests.sh
With this changes support for NodeJS 10 is dropped
> SDCB-8698 Update JS server side sample

- samples/testing-frameworks/appium/client-side/python/.gitignore
- samples/testing-frameworks/appium/client-side/python/README.md
- samples/testing-frameworks/appium/client-side/python/base_test.py
- samples/testing-frameworks/appium/client-side/python/tests/bitbar_android.py
- samples/testing-frameworks/appium/client-side/python/tests/bitbar_biometrics_android.py
- samples/testing-frameworks/appium/client-side/python/tests/bitbar_biometrics_ios.py
- samples/testing-frameworks/appium/client-side/python/tests/bitbar_chrome.py
- samples/testing-frameworks/appium/client-side/python/tests/bitbar_ios.py
- samples/testing-frameworks/appium/client-side/python/tests/bitbar_safari.py
- samples/testing-frameworks/appium/client-side/python/upload.py
- Refactored capabilities for all python cs samples
- Few minor changes (pointed out in comments)
- ~~Added `"bitbar_appiumVersion" = "2.0"` capability to run appium 2.0 as default~~
> SDCB-9995-[Appium. 2.0 Support] Python CS sample

- samples/testing-frameworks/appium/client-side/javascript/biometricInstrumentation/webdriver.io/android.wdio.conf.js
- samples/testing-frameworks/appium/client-side/javascript/biometricInstrumentation/webdriver.io/ios.wdio.conf.js
- samples/testing-frameworks/appium/client-side/javascript/nightwatch_web_example/nightwatch.json
- samples/testing-frameworks/appium/client-side/javascript/nightwatch_web_example/package-lock.json
- samples/testing-frameworks/appium/client-side/javascript/nightwatch_web_example/tests/example_test.js
- samples/testing-frameworks/appium/client-side/javascript/webdriver.io/wdio.conf.js
-Refactored capabilities
-Added vendor prefixes
-Removed step `.waitForElementPresent` in `example_test.js` as it seems to doesn't work anymore and is not crucial for test.
> SDCB-9994 [Appium 2.0 Support] JavaScript CS sample

- samples/testing-frameworks/appium/server-side/python/.gitignore
- samples/testing-frameworks/appium/server-side/python/BitBarAppiumTest.py
- samples/testing-frameworks/appium/server-side/python/README.md
- samples/testing-frameworks/appium/server-side/python/run-tests_android.sh
- samples/testing-frameworks/appium/server-side/python/run-tests_ios.sh
based on #510 
just improved some minor things. @eryk-tkaczewski is responsible for most of major changes
> SDCB-9999 adjust python server side sample
